name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  iri-edp:
    name: IRI EDP
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends gnuplot
      
    - name: Build project
      run: |
        cd iri-edp/src
        make -j
      
    - name: Run cases
      run: |
        cd iri-edp/src
        ./iri -c 1 -o case1.csv
        ./iri -c 2 -o case2.csv
        
    - name: Upload output files
      uses: actions/upload-artifact@v4
      with:
        name: iri-edp-output
        path: |
          iri-edp/src/case1.csv
          iri-edp/src/case2.csv
        retention-days: 1

    - name: Upload plots
      uses: actions/upload-artifact@v4
      with:
        name: iri-edp-plots
        path: |
          iri-edp/src/edp.png
          iri-edp/src/temp.png
          iri-edp/src/ratio.png
        retention-days: 1

  mandelbrot:
    name: Mandelbrot
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Node.js dependencies
      run: |
        cd mandelbrot/nodejs
        npm install

    - name: Set up Python (uv)
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'

    - name: Generate Mandelbrot images
      run: |
        cd mandelbrot
        ./plots.sh

    - name: Upload Mandelbrot images
      uses: actions/upload-artifact@v4
      with:
        name: mandelbrot-images
        path: |
          mandelbrot/default.jpg
          mandelbrot/seahorse-tail.jpg
          mandelbrot/seahorse-valley.jpg
        retention-days: 1
