name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  iri-edp:
    name: IRI EDP
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gnuplot

      - name: Build project
        run: |
          cd iri-edp/src
          make -j

      - name: Run cases
        run: |
          cd iri-edp/src
          ./plots.sh

      - name: Upload output files
        uses: actions/upload-artifact@v4
        with:
          name: iri-edp-output
          path: |
            iri-edp/src/*.csv
          if-no-files-found: error
          retention-days: 1

      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: iri-edp-plots
          path: |
            iri-edp/src/*.png
          if-no-files-found: error
          retention-days: 1

  mandelbrot:
    name: Mandelbrot
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Node.js dependencies
        run: |
          cd mandelbrot/nodejs
          npm install

      - name: Set up Python (uv)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: |
            mandelbrot/plot.py

      - name: Generate Mandelbrot images
        run: |
          cd mandelbrot
          ./plots.sh

      - name: Upload Mandelbrot images
        uses: actions/upload-artifact@v4
        with:
          name: mandelbrot-images
          path: |
            mandelbrot/*.jpg
          if-no-files-found: error
          retention-days: 1

  interp:
    name: Interpolation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (uv)
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: |
            interp/plots.py

      - name: Generate the plots
        run: |
          cd interp
          uv run ./plots.py

      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: interp-plots
          path: |
            interp/*.png
          if-no-files-found: error
          retention-days: 1

  coord-tran:
    name: Coordinate Transformations
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euo pipefail {0}

    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: |
          cd coord-tran/src
          make

      - name: Run tests
        run: |
          cd coord-tran/src
          make test
